version: "3.1"
name: cool-profile-system

services:
  backend:
    container_name: backend-service
    restart: always
    networks:
      - db-network
    build:
      context: .
    environment:
      DB_HOST: my-sql-service
    depends_on:
      - my-sql
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: index.js
          target: /app/index.js
          action: sync+restart

        - path: src
          target: /app/src
          action: sync+restart

        - path: package-lock.json
          action: rebuild

        - path: package.json
          action: rebuild

  my-sql:
    container_name: my-sql-service
    image: mysql
    restart: always
    ports:
     - "3306:3306"
    networks:
      - db-network
    environment:
      MYSQL_ROOT_PASSWORD: mysql-root
      MYSQL_DATABASE: mysql
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql

networks:
  db-network: