name: cool-profile-system

services:
  backend:
    container_name: backend-service
    build:
      context: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: src
          target: /app/src
          action: sync+restart

        - path: package-lock.json
          action: rebuild

        - path: package.json
          action: rebuild