version: "3.1"
name: cool-profile-system

services:
  backend:
    container_name: backend-service
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: src
          target: /app/src
          action: sync+restart

        - path: package-lock.json
          action: rebuild

        - path: package.json
          action: rebuild

  # my_sql:
  #   container_name: my_sql-service
  #   image: mysql
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
